/* Academic Portfolio & Resume Data (English Edition) */
window.RESUME_DATA = {
  profile: {
    name: "Xuancheng Jin",
    chineseName: "金宣成",
    kicker: "Academic CV · Portfolio",
    role: "Jilin University · College of Earth Sciences · Land Resource Management",
    intro: "Master's student in Land Resource Management at Jilin University. Research focuses on black soil organic carbon, cropland conservation, ecosystem services, and satellite remote sensing inversion. Experienced in spatial modeling, machine learning, scientific writing, and research project management.",
    researchStatement: "Remote sensing and spatial modelling for soil and ecosystem assessment.",
    resumePdf: "./files/金宣成简历.pdf",
    affiliation: "Jilin University · College of Earth Sciences",
    avatar: "./images/profile.jpg",
    email: "jinxuancheng727@gmail.com",
    github: "https://github.com/Simon727",
    orcid: "https://orcid.org/0009-0009-0583-6142",
    facts: [
      { value: "M.Sc.", label: "Degree Candidate" },
      { value: "Top 1%", label: "Undergraduate Rank (1/70)" },
      { value: "1st Author", label: "SCI Top Journal Paper" },
      { value: "12", label: "Software Copyrights" },
    ],
  },
  highlights: [
    "Soil Organic Carbon Mapping",
    "Remote Sensing & Spatial Analysis",
    "Machine Learning & Deep Learning",
    "Ecosystem Services Assessment",
  ],
  research: [
    {
      type: "First Author · CAS Tier 1 Top / Q1",
      year: "2026",
      title: "Uncertainty in ecosystem service value assessment caused by spatial scale and aggregation rules: a multiscale study of Northeast China from 2000 to 2024",
      meta: "Ecological Indicators 190 (2026) 115426 · First Author",
      detail: "Quantified the mechanisms and uncertainties of spatial scale evolution and aggregation rules on ecosystem service value evaluation and spatial heterogeneity in Northeast China.",
      url: "https://doi.org/10.1016/j.ecolind.2026.115426",
    },
    {
      type: "Co-Author · CAS Tier 3",
      year: "2026",
      title: "Integrating transformer-based learning and Sentinel-2 bare soil composites for soil organic carbon mapping in the black soil region of Northeast China",
      meta: "Scientific Reports 16, 3784 (2026) · Third Author",
      detail: "Coupled Sentinel-2 bare soil composite imagery with Transformer-based TabPFN to achieve high-precision digital mapping of soil organic carbon under small-sample conditions in the black soil region.",
      url: "https://doi.org/10.1038/s41598-025-33682-4",
    },
    {
      type: "Chinese Core Journal",
      year: "2025",
      title: "Delineation of Ecological Restoration Zoning in Salt-Affected Areas of Western Jilin Province Based on Habitat Quality Changes",
      meta: "Journal of Agricultural Resources and Environment, 2025, 42(1): 33-43 · Second Author (Student First Author)",
      detail: "Coupled land use transition matrix and InVEST model to reveal the spatiotemporal differentiation of habitat quality in fragile saline-alkali areas of western Jilin, constructing multi-level ecological restoration zoning strategies.",
      url: "https://doi.org/10.13254/j.jare.2023.0658",
    },
    {
      type: "Utility Model Patent",
      year: "2023",
      title: "A Collection Device for Soil Sample Sampling",
      meta: "First Inventor · Patent No. ZL 2022 2 2816456.8",
      detail: "Awarded 1 National Utility Model Patent as the first inventor.",
    },
    {
      type: "Principal Investigator",
      year: "2026",
      title: "Research on Multi-scale Inversion Method of Soil Organic Carbon in Black Soil Region Integrating Spatial Clustering and Deep Learning",
      meta: "Jilin University Graduate Innovation Research Project · No. 2026CX229",
      detail: "Leading research on multi-scale soil organic carbon inversion in the black soil region using synergistic spatial clustering and deep learning approaches.",
    },
    {
      type: "Principal Investigator",
      year: "2023",
      title: "Spatiotemporal Characteristics and Driving Mechanisms of Green Utilization Transition of Cropland in Main Grain-Producing Areas of China",
      meta: "Provincial University Student Science & Technology Innovation Fund",
      detail: "Led research on identifying spatiotemporal patterns and driving mechanisms of green cropland utilization transition in major grain-producing regions.",
    },
    {
      type: "Co-Investigator",
      year: "2025",
      title: "Multi-scale Ecological Compensation for Cropland Protection in Salt-Affected Areas of Western Jilin Based on the 'Trinity' Framework",
      meta: "Social Science Research Project of Jilin Provincial Department of Education · No. JJKH20240478SK",
      detail: "Participated as a key member in multi-scale cropland conservation and ecological compensation studies; project passed final appraisal and acceptance.",
    },
    {
      type: "Research Project",
      year: "2025",
      title: "Remote Sensing Identification of Spatial Variation in Soil Organic Carbon under Different Cultivation Years in Hulunbuir Farm Area",
      meta: "College of Earth Sciences, Jilin University · Technical Report Author",
      detail: "Conducted remote sensing reconstruction of cropland cultivation history, soil organic carbon inversion modeling, and digital mapping.",
    },
    {
      type: "Software Copyright",
      year: "2022—2025",
      title: "12 National Computer Software Copyright Registrations",
      meta: "First Copyright Holder & Key Contributor",
      detail: "Registered a total of 12 Computer Software Copyrights with the National Copyright Administration as the primary or co-developer.",
    },
  ],
  education: [
    {
      period: "2025.09 — Present",
      school: "Jilin University",
      college: "College of Earth Sciences",
      major: "Land Resource Management",
      degree: "M.Sc. Candidate",
      grade: "Research Focus: Remote Sensing & Soil Carbon · Graduate 1st-Class Scholarship",
      details: [
        "Digital Soil Mapping & Soil Organic Carbon Inversion",
        "Spatial Scale Evolution & Aggregation Rules",
        "Conservation and Sustainable Utilization of Black Soil Resources",
      ],
    },
    {
      period: "2021.09 — 2025.06",
      school: "Jilin Agricultural University",
      college: "College of Economics and Management",
      major: "Land Resource Management",
      degree: "B.Sc.",
      grade: "GPA: 4.28 · Rank: 1 / 70 · National Scholarship & Outstanding Graduate",
      details: [
        "Land Use Planning",
        "Geographic Information Systems (GIS)",
        "Applied Remote Sensing Technology",
        "Land Economics",
      ],
    },
  ],
  skills: [
    {
      title: "Language Proficiency",
      items: [
        "CATTI Level-3 English Translation Professional Qualification (State Professional Credential)",
        "College English Test Band 4 (CET-4): 595",
        "College English Test Band 6 (CET-6): 581",
        "Proficient in English Academic Literature Reading & SCI Paper Writing",
      ],
    },
    {
      title: "Professional Skills",
      items: [
        "ArcGIS & ArcGIS Pro",
        "Google Earth Engine (GEE)",
        "Sentinel-2 / Landsat Remote Sensing Inversion",
        "AutoCAD",
        "Origin Scientific Plotting",
      ],
    },
    {
      title: "Models & Algorithms",
      items: [
        "Python (NumPy, Pandas, Scikit-learn)",
        "TabPFN Foundation Model",
        "InVEST Ecosystem Model",
        "PLUS Land Use Simulation",
        "Geodetector & Spatial Statistics",
      ],
    },
    {
      title: "Scientific Writing",
      items: [
        "National Patent Specifications (Invention & Utility Model)",
        "Computer Software Copyright Applications",
        "Academic & Research Project Proposals",
      ],
    },
  ],
  honors: [
    { year: "2024", title: "National Scholarship for Undergraduate Students", detail: "Ministry of Education of China · Highest National Honor" },
    { year: "2024", title: "First Prize in National Mathematical Modeling Contest (Jilin Division)", detail: "Undergraduate Group · Team Captain" },
    { year: "2023", title: "First Prize in National English Competition for College Students (NECCS)", detail: "National Level" },
    { year: "2021", title: "Grand Prize in National College English Ability Challenge Finals", detail: "National Level" },
    { year: "2025", title: "Silver Award in FLTRP·ETIC Cup 'Understanding Contemporary China' Contest", detail: "Comprehensive English Category" },
    { year: "2023", title: "Third Prize in FLTRP·ETIC Cup National College Reading Contest", detail: "National Finalist" },
    { year: "2023", title: "Third Prize in SFLEP Cup Intercultural Competence Contest (Jilin Division)" },
    { year: "2026", title: "CATTI Level-3 English Translation Professional Qualification", detail: "State Professional Technical Qualification" },
    { year: "2026", title: "Invited Peer Reviewer for Springer Nature", detail: "SCI Journal: Functional & Integrative Genomics" },
    { year: "2025", title: "Outstanding Graduate of Jilin Agricultural University" },
    { year: "2022—2023", title: "University-Level Outstanding Undergraduate, Exemplary Youth League Member, and Model Student" },
    { year: "Scholarships", title: "1× Graduate 1st-Class Scholarship, 5× Undergraduate 1st-Class Scholarships, 2× Subject Excellence Scholarships" },
  ],
  experience: [
    {
      period: "2026.06 — 2026.09",
      organization: "Mudanjiang Natural Resources Comprehensive Survey Center, China Geological Survey",
      role: "Research Intern",
      detail: "Engaged in remote sensing extraction, soil organic carbon pool identification, and field soil survey data processing.",
    },
    {
      period: "2023.07 — 2023.08",
      organization: "Wenling Municipal Bureau of Natural Resources and Planning, Zhejiang Province",
      role: "Professional Intern",
      detail: "Participated in land space planning compilation, cadastre survey verification, and geospatial data administration.",
    },
  ],
};
