/* 英文学术简历数据文件：与中文版保持严格 1:1 内容与结构一致 */
window.RESUME_DATA = {
  profile: {
    name: "Xuancheng Jin",
    chineseName: "金宣成",
    kicker: "Academic Resume",
    role: "Jilin University · College of Earth Sciences · Land Resource Management",
    intro: "Master's student in Land Resource Management at Jilin University, focusing on black soil organic carbon, cropland conservation, ecosystem services, and remote sensing inversion. Experienced in spatial analysis, machine learning, scientific writing, and project research.",
    researchStatement: "Remote sensing and spatial modelling for soil and ecosystem assessment.",
    resumePdf: "./files/金宣成简历.pdf",
    affiliation: "Jilin University · College of Earth Sciences",
    avatar: "./images/profile.jpg",
    email: "jinxuancheng727@gmail.com",
    github: "https://github.com/Simon727",
    orcid: "https://orcid.org/0009-0009-0583-6142",
    facts: [],
  },
  highlights: [
    "Soil Organic Carbon Mapping",
    "Remote Sensing & Spatial Analysis",
    "Machine Learning & Deep Learning",
    "Ecosystem Services Assessment",
  ],
  research: [
    {
      type: "CAS Tier 1", year: "2026",
      title: "Uncertainty in ecosystem service value assessment caused by spatial scale and aggregation rules: a multiscale study of Northeast China from 2000 to 2024",
      meta: "Ecological Indicators 190 (2026) 115426 · First Author",
      detail: "Quantifying the effects of spatial scale and aggregation rules on ecosystem service value estimation and spatial interpretation in Northeast China.",
      url: "https://doi.org/10.1016/j.ecolind.2026.115426",
    },
    {
      type: "CAS Tier 3", year: "2026",
      title: "Integrating transformer-based learning and Sentinel-2 bare soil composites for soil organic carbon mapping in the black soil region of Northeast China",
      meta: "Scientific Reports 16, 3784 (2026) · Third Author",
      detail: "Coupled Sentinel-2 bare soil composites and TabPFN to achieve high-precision digital mapping of soil organic carbon under small-sample conditions in the black soil region of Northeast China.",
      url: "https://doi.org/10.1038/s41598-025-33682-4",
    },
    {
      type: "Chinese Core Journal", year: "2025",
      title: "Delineation of ecological restoration zoning in salt-affected areas of western Jilin Province based on habitat quality changes",
      meta: "Journal of Agricultural Resources and Environment 2025, 42(1): 33-43 · Second Author",
      detail: "Investigating habitat quality dynamics and ecological restoration zoning in the saline-alkali region of western Jilin Province.",
      url: "https://doi.org/10.13254/j.jare.2023.0658",
    },
    {
      type: "Utility Model Patent", year: "2023",
      title: "A collection device for soil sample sampling",
      meta: "First Inventor · Patent No. ZL 2022 2 2816456.8",
      detail: "Obtained 1 utility model patent as the first inventor.",
    },
    {
      type: "Principal Project", year: "2026",
      title: "Research on multi-scale fusion inversion method of soil organic carbon in black soil region integrating spatial clustering and deep learning",
      meta: "Jilin University Graduate Innovation Research Project · Project No. 2026CX229",
      detail: "Targeting multi-scale soil organic carbon inversion in black soil regions, exploring collaborative applications of spatial clustering and deep learning approaches.",
    },
    {
      type: "Principal Project", year: "2023",
      title: "Spatiotemporal characteristics and driving mechanisms of green utilization transition of cropland in main grain-producing areas of China",
      meta: "Provincial College Student Science & Technology Innovation Fund",
      detail: "Principal investigator identifying spatiotemporal patterns and driving mechanisms of green cropland utilization transition in main grain-producing areas.",
    },
    {
      type: "Participated Project", year: "2025",
      title: "Multi-scale ecological compensation for cropland protection in salt-affected areas of western Jilin Province based on the 'Trinity' framework",
      meta: "Social Science Research Project of Jilin Provincial Department of Education · Project No. JJKH20240478SK",
      detail: "Participated as a key member in research on multi-scale cropland conservation and ecological compensation; the project has successfully concluded.",
    },
    {
      type: "Research Project", year: "2025",
      title: "Remote sensing identification of spatial differences in soil organic carbon under different cultivation years in Hulunbuir farm area",
      meta: "College of Earth Sciences, Jilin University · Report Contributor",
      detail: "Participated in remote sensing reconstruction of cropland reclamation history, soil organic carbon inversion modeling, and spatial mapping.",
    },
    {
      type: "Software Copyright", year: "2022—2025",
      title: "12 Computer Software Copyright Registrations",
      meta: "First Author and Registered Contributor",
      detail: "Obtained 12 computer software copyright registrations as the primary or contributing developer.",
    },
  ],
  education: [
    {
      period: "2025.09 — Present", school: "Jilin University", college: "College of Earth Sciences",
      major: "Land Resource Management", degree: "Master's Student", grade: "Research Focus: Remote Sensing & Soil Carbon",
      details: ["Soil organic carbon remote sensing inversion", "Spatial scale effects", "Conservation and utilization of black soil resources"],
    },
    {
      period: "2021.09 — 2025.06", school: "Jilin Agricultural University", college: "College of Economics and Management",
      major: "Land Resource Management", degree: "Bachelor", grade: "GPA 4.28 · Major Rank 1 / 70",
      details: ["Land use planning", "Geographic Information Systems (GIS)", "Applied remote sensing technology", "Land economics"],
    },
  ],
  skills: [
    { title: "Foreign Language", items: ["CATTI Level-3 English Translation", "CET-4 595", "CET-6 581"] },
  ],
  honors: [
    { year: "2024", title: "National Scholarship for Undergraduate Students", detail: "Academic Year 2023—2024" },
    { year: "2024", title: "First Prize in National Mathematical Modeling Contest (Jilin Division)", detail: "Undergraduate Group · Team Captain" },
    { year: "2023", title: "First Prize in National English Competition for College Students (NECCS)", detail: "National Level" },
    { year: "2021", title: "Grand Prize in National College English Ability Challenge Finals", detail: "National Level" },
    { year: "2025", title: "Silver Award in FLTRP·ETIC Cup National Foreign Language Contest", detail: "English Comprehensive Category" },
    { year: "2023", title: "Third Prize in FLTRP·ETIC Cup National College Reading Contest", detail: "National Level" },
    { year: "2023", title: "Third Prize in 6th SFLEP Cup National College Intercultural Competence Contest (Jilin Division)" },
    { year: "2026", title: "CATTI English Level-3 Translation Professional Qualification", detail: "National Professional Qualification" },
    { year: "2026", title: "Springer Nature Reviewer", detail: "Functional & Integrative Genomics" },
    { year: "2025", title: "Outstanding Graduate of Jilin Agricultural University" },
    { year: "2022—2023", title: "Honorary Titles of Outstanding Undergraduate, Model Youth League Member, and Model Student" },
    { year: "M.Sc. Period", title: "First-Class Professional Scholarship (1 time)" },
    { year: "B.Sc. Period", title: "First-Class Professional Scholarship (5 times), Subject Excellence Scholarship (2 times)" },
  ],
  experience: [
    {
      period: "2026.06 — 2026.09", organization: "Mudanjiang Natural Resources Comprehensive Survey Center, China Geological Survey",
      role: "Research Internship", detail: "Assisted in multispectral remote sensing data extraction, soil carbon pool remote sensing identification, and related project research.",
    },
    {
      period: "2023.07 — 2023.08", organization: "Wenling Municipal Bureau of Natural Resources and Planning, Zhejiang Province",
      role: "Internship", detail: "Participated in practical work related to natural resources and land space planning.",
    },
  ],
};
